services:
  visualpy:
    build:
      context: .
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    container_name: visualpy
    restart: always
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
    name: caddy_net
