blank_issues_enabled: false
contact_links:
  - name: Contributing guide
    url: https://github.com/Lexi-Energy/visualpy/blob/main/CONTRIBUTING.md
    about: Not sure where to start? Read our contributing guide first.
